### ISSUE TITLE
Custom HTTP-Headers for Readiness-Checks ignored

### ISSUE THREAD

**Issue by felixbuenemann** [deis/workflow-cli#279]
Custom HTTP-Headers are ignored when trying to create a readiness check on Workflow v2.9.0 on K8s 1.4.6 with CLI v2.9.0-eb21ef2 (current master).

**Example:**
```sh
deis healthchecks:set readiness httpGet 5000 \
  --path /healthz \
  --type web \
  --initial-delay-timeout=20 \
  --timeout-seconds=5 \
  --header="X-Forwarded-Proto:https"
```

This is using the format listed in the specs, I also tried with `--header="X-Forwarded-Proto=https"`, which is the format listed in the docs.

The generated readiness probe in the app's deployment looks like:

```yaml
readinessProbe: 
  failureThreshold: 3
  httpGet: 
    path: /healthz
    port: 5000
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```

Note that `httpHeaders` is missing.

The *expected* readiness probe would look like:

```yaml
readinessProbe:
  failureThreshold: 3
  httpGet:
    httpHeaders:
    - name: X-Forwarded-Proto
      value: https
    path: /healthz
    port: 5000
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```

Prettified dump of the JSON I captured from the POST /v2/apps/:name/config/ request using tcpdump:

```json
{
  "healthcheck": {
    "web": {
      "readinessProbe": {
        "initialDelaySeconds": 20,
        "timeoutSeconds": 5,
        "periodSeconds": 10,
        "successThreshold": 1,
        "failureThreshold": 3,
        "httpGet": {
          "path": "/healthz",
          "port": 5000
        }
      }
    }
  }
}
```

There's no header info here either.

Btw. it would be really helpful if the correct format for specifying headers would be shown when running `deis healthchecks:set --help`.
